import { inArray } from "drizzle-orm";
import type { DatabaseContext } from "./database.js";

type DemoCarSeed = {
  licensePlate: string;
  brand: string;
  model: string;
  year: number;
  category: "CITADINE" | "BERLINE" | "SUV" | "MONOSPACE" | "UTILITAIRE" | "LUXE" | "SPORT" | "4X4";
  fuelType: "ESSENCE" | "DIESEL" | "HYBRIDE" | "ELECTRIQUE" | "GPL";
  transmission: "MANUELLE" | "AUTOMATIQUE";
  seats: number;
  doors: number;
  airConditioning: boolean;
  dailyPrice: number;
  weeklyPrice: number;
  monthlyPrice: number;
  depositAmount: number;
  mileageLimit: number;
  city: string;
  agencyName: string;
  address: string;
  mainImageUrl: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  seoSlug: string;
};

const demoFleet: DemoCarSeed[] = [
  {
    licensePlate: "AA-100-AA",
    brand: "Toyota",
    model: "Corolla",
    year: 2023,
    category: "BERLINE",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 4,
    airConditioning: true,
    dailyPrice: 320,
    weeklyPrice: 1790,
    monthlyPrice: 5890,
    depositAmount: 3000,
    mileageLimit: 250,
    city: "Casablanca",
    agencyName: "Agence Casablanca Centre",
    address: "Boulevard Mohammed V, Casablanca",
    mainImageUrl: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1400&q=80",
    description: "Berline fiable et confortable, parfaite pour la ville et les trajets interurbains.",
    seoTitle: "Toyota Corolla 2023 - Location Casablanca",
    seoDescription: "Location d'une Toyota Corolla 2023 a Casablanca, automatique, confortable et economique.",
    seoSlug: "toyota-corolla-2023-casablanca",
  },
  {
    licensePlate: "AA-101-AA",
    brand: "Renault",
    model: "Clio",
    year: 2024,
    category: "CITADINE",
    fuelType: "DIESEL",
    transmission: "MANUELLE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 240,
    weeklyPrice: 1350,
    monthlyPrice: 4290,
    depositAmount: 2000,
    mileageLimit: 200,
    city: "Rabat",
    agencyName: "Agence Rabat Agdal",
    address: "Avenue Annakhil, Rabat",
    mainImageUrl: "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80",
    description: "Citadine agile et sobre, ideale pour les deplacements du quotidien.",
    seoTitle: "Renault Clio 2024 - Location Rabat",
    seoDescription: "Location d'une Renault Clio 2024 a Rabat, economique, compacte et facile a conduire.",
    seoSlug: "renault-clio-2024-rabat",
  },
  {
    licensePlate: "AA-102-AA",
    brand: "Peugeot",
    model: "3008",
    year: 2024,
    category: "SUV",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 690,
    weeklyPrice: 3990,
    monthlyPrice: 12900,
    depositAmount: 5000,
    mileageLimit: 300,
    city: "Marrakech",
    agencyName: "Agence Marrakech Gueliz",
    address: "Boulevard Abdelkrim Khattabi, Marrakech",
    mainImageUrl: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=80",
    description: "SUV polyvalent avec position de conduite haute et excellente tenue de route.",
    seoTitle: "Peugeot 3008 2024 - Location Marrakech",
    seoDescription: "Location d'une Peugeot 3008 2024 a Marrakech, SUV moderne et confortable.",
    seoSlug: "peugeot-3008-2024-marrakech",
  },
  {
    licensePlate: "AA-103-AA",
    brand: "Dacia",
    model: "Duster",
    year: 2024,
    category: "SUV",
    fuelType: "DIESEL",
    transmission: "MANUELLE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 430,
    weeklyPrice: 2490,
    monthlyPrice: 7990,
    depositAmount: 3000,
    mileageLimit: 300,
    city: "Agadir",
    agencyName: "Agence Agadir Centre",
    address: "Avenue Hassan II, Agadir",
    mainImageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80",
    description: "SUV robuste et pratique, adaptee aux escapades et aux longs trajets.",
    seoTitle: "Dacia Duster 2024 - Location Agadir",
    seoDescription: "Location d'une Dacia Duster 2024 a Agadir, robuste, pratique et spacieuse.",
    seoSlug: "dacia-duster-2024-agadir",
  },
  {
    licensePlate: "AA-104-AA",
    brand: "Hyundai",
    model: "Tucson",
    year: 2023,
    category: "SUV",
    fuelType: "HYBRIDE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 720,
    weeklyPrice: 4190,
    monthlyPrice: 13500,
    depositAmount: 6000,
    mileageLimit: 280,
    city: "Tanger",
    agencyName: "Agence Tanger Marina",
    address: "Boulevard Mohammed VI, Tanger",
    mainImageUrl: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=80",
    description: "SUV hybride moderne avec un niveau d'equipement premium.",
    seoTitle: "Hyundai Tucson 2023 - Location Tanger",
    seoDescription: "Location d'une Hyundai Tucson 2023 a Tanger, hybride et spacieuse.",
    seoSlug: "hyundai-tucson-2023-tanger",
  },
  {
    licensePlate: "AA-105-AA",
    brand: "Kia",
    model: "Picanto",
    year: 2023,
    category: "CITADINE",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 4,
    doors: 5,
    airConditioning: true,
    dailyPrice: 210,
    weeklyPrice: 1190,
    monthlyPrice: 3690,
    depositAmount: 1800,
    mileageLimit: 180,
    city: "Casablanca",
    agencyName: "Agence Casablanca Centre",
    address: "Boulevard Mohammed V, Casablanca",
    mainImageUrl: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1400&q=80",
    description: "Petite citadine economique, parfaite pour la ville et les parkings serres.",
    seoTitle: "Kia Picanto 2023 - Location Casablanca",
    seoDescription: "Location d'une Kia Picanto 2023 a Casablanca, petite, economique et pratique.",
    seoSlug: "kia-picanto-2023-casablanca",
  },
  {
    licensePlate: "AA-106-AA",
    brand: "Volkswagen",
    model: "Passat",
    year: 2022,
    category: "BERLINE",
    fuelType: "DIESEL",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 4,
    airConditioning: true,
    dailyPrice: 560,
    weeklyPrice: 3190,
    monthlyPrice: 10300,
    depositAmount: 4500,
    mileageLimit: 260,
    city: "Rabat",
    agencyName: "Agence Rabat Agdal",
    address: "Avenue Annakhil, Rabat",
    mainImageUrl: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=80",
    description: "Berline spacieuse et sobre, parfaite pour les longs trajets confortables.",
    seoTitle: "Volkswagen Passat 2022 - Location Rabat",
    seoDescription: "Location d'une Volkswagen Passat 2022 a Rabat, confortable et elegante.",
    seoSlug: "volkswagen-passat-2022-rabat",
  },
  {
    licensePlate: "AA-107-AA",
    brand: "BMW",
    model: "320d",
    year: 2024,
    category: "LUXE",
    fuelType: "DIESEL",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 4,
    airConditioning: true,
    dailyPrice: 1100,
    weeklyPrice: 6490,
    monthlyPrice: 20900,
    depositAmount: 12000,
    mileageLimit: 220,
    city: "Marrakech",
    agencyName: "Agence Marrakech Gueliz",
    address: "Boulevard Abdelkrim Khattabi, Marrakech",
    mainImageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80",
    description: "Berline premium avec finition soignee et conduite sportive.",
    seoTitle: "BMW 320d 2024 - Location Marrakech",
    seoDescription: "Location d'une BMW 320d 2024 a Marrakech, premium et confortable.",
    seoSlug: "bmw-320d-2024-marrakech",
  },
  {
    licensePlate: "AA-108-AA",
    brand: "Mercedes-Benz",
    model: "GLC",
    year: 2024,
    category: "LUXE",
    fuelType: "HYBRIDE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 1350,
    weeklyPrice: 7990,
    monthlyPrice: 24900,
    depositAmount: 15000,
    mileageLimit: 220,
    city: "Casablanca",
    agencyName: "Agence Casablanca Centre",
    address: "Boulevard Mohammed V, Casablanca",
    mainImageUrl: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=80",
    description: "SUV luxe raffine, tres confortable pour les trajets premium.",
    seoTitle: "Mercedes-Benz GLC 2024 - Location Casablanca",
    seoDescription: "Location d'une Mercedes-Benz GLC 2024 a Casablanca, luxe et elegante.",
    seoSlug: "mercedes-benz-glc-2024-casablanca",
  },
  {
    licensePlate: "AA-109-AA",
    brand: "Nissan",
    model: "X-Trail",
    year: 2023,
    category: "SUV",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 7,
    doors: 5,
    airConditioning: true,
    dailyPrice: 790,
    weeklyPrice: 4590,
    monthlyPrice: 14900,
    depositAmount: 7000,
    mileageLimit: 300,
    city: "Agadir",
    agencyName: "Agence Agadir Centre",
    address: "Avenue Hassan II, Agadir",
    mainImageUrl: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1400&q=80",
    description: "SUV familial avec 7 places et une belle modularite.",
    seoTitle: "Nissan X-Trail 2023 - Location Agadir",
    seoDescription: "Location d'une Nissan X-Trail 2023 a Agadir, familiale et polyvalente.",
    seoSlug: "nissan-x-trail-2023-agadir",
  },
  {
    licensePlate: "AA-110-AA",
    brand: "Honda",
    model: "Civic",
    year: 2024,
    category: "BERLINE",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 4,
    airConditioning: true,
    dailyPrice: 410,
    weeklyPrice: 2390,
    monthlyPrice: 7590,
    depositAmount: 3500,
    mileageLimit: 260,
    city: "Casablanca",
    agencyName: "Agence Casablanca Centre",
    address: "Boulevard Mohammed V, Casablanca",
    mainImageUrl: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1400&q=80",
    description: "Berline moderne et precise, agreable pour la ville comme pour la route.",
    seoTitle: "Honda Civic 2024 - Location Casablanca",
    seoDescription: "Location d'une Honda Civic 2024 a Casablanca, elegante et dynamique.",
    seoSlug: "honda-civic-2024-casablanca",
  },
  {
    licensePlate: "AA-111-AA",
    brand: "Mazda",
    model: "CX-5",
    year: 2024,
    category: "SUV",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 780,
    weeklyPrice: 4490,
    monthlyPrice: 14500,
    depositAmount: 7000,
    mileageLimit: 300,
    city: "Tanger",
    agencyName: "Agence Tanger Marina",
    address: "Boulevard Mohammed VI, Tanger",
    mainImageUrl: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=80",
    description: "SUV raffine avec un bon confort et une conduite tres fluide.",
    seoTitle: "Mazda CX-5 2024 - Location Tanger",
    seoDescription: "Location d'une Mazda CX-5 2024 a Tanger, confortable et polyvalente.",
    seoSlug: "mazda-cx5-2024-tanger",
  },
  {
    licensePlate: "AA-112-AA",
    brand: "Skoda",
    model: "Octavia",
    year: 2023,
    category: "BERLINE",
    fuelType: "DIESEL",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 4,
    airConditioning: true,
    dailyPrice: 520,
    weeklyPrice: 2990,
    monthlyPrice: 9650,
    depositAmount: 4000,
    mileageLimit: 260,
    city: "Rabat",
    agencyName: "Agence Rabat Agdal",
    address: "Avenue Annakhil, Rabat",
    mainImageUrl: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=80",
    description: "Berline spacieuse et sobre, tres appreciee pour les grands trajets.",
    seoTitle: "Skoda Octavia 2023 - Location Rabat",
    seoDescription: "Location d'une Skoda Octavia 2023 a Rabat, spacieuse et elegante.",
    seoSlug: "skoda-octavia-2023-rabat",
  },
  {
    licensePlate: "AA-113-AA",
    brand: "Ford",
    model: "Focus",
    year: 2023,
    category: "BERLINE",
    fuelType: "ESSENCE",
    transmission: "MANUELLE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 360,
    weeklyPrice: 2090,
    monthlyPrice: 6690,
    depositAmount: 3000,
    mileageLimit: 240,
    city: "Fes",
    agencyName: "Agence Fes Centre",
    address: "Avenue Hassan II, Fes",
    mainImageUrl: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=80",
    description: "Compacte fiable et economique, parfaite pour les trajets quotidiens.",
    seoTitle: "Ford Focus 2023 - Location Fes",
    seoDescription: "Location d'une Ford Focus 2023 a Fes, pratique et agreable a conduire.",
    seoSlug: "ford-focus-2023-fes",
  },
  {
    licensePlate: "AA-114-AA",
    brand: "Toyota",
    model: "RAV4",
    year: 2024,
    category: "SUV",
    fuelType: "HYBRIDE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 850,
    weeklyPrice: 4990,
    monthlyPrice: 15900,
    depositAmount: 8000,
    mileageLimit: 300,
    city: "Marrakech",
    agencyName: "Agence Marrakech Gueliz",
    address: "Boulevard Abdelkrim Khattabi, Marrakech",
    mainImageUrl: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1400&q=80",
    description: "SUV hybride fiable avec un bon volume interieur et une vraie polyvalence.",
    seoTitle: "Toyota RAV4 2024 - Location Marrakech",
    seoDescription: "Location d'une Toyota RAV4 2024 a Marrakech, hybride et familiale.",
    seoSlug: "toyota-rav4-2024-marrakech",
  },
  {
    licensePlate: "AA-115-AA",
    brand: "Audi",
    model: "A3",
    year: 2024,
    category: "BERLINE",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 4,
    airConditioning: true,
    dailyPrice: 690,
    weeklyPrice: 3990,
    monthlyPrice: 12900,
    depositAmount: 6000,
    mileageLimit: 260,
    city: "Casablanca",
    agencyName: "Agence Casablanca Centre",
    address: "Boulevard Mohammed V, Casablanca",
    mainImageUrl: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=80",
    description: "Berline premium au design net et au comportement tres equilibré.",
    seoTitle: "Audi A3 2024 - Location Casablanca",
    seoDescription: "Location d'une Audi A3 2024 a Casablanca, compacte et premium.",
    seoSlug: "audi-a3-2024-casablanca",
  },
  {
    licensePlate: "AA-116-AA",
    brand: "Lexus",
    model: "NX",
    year: 2024,
    category: "LUXE",
    fuelType: "HYBRIDE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 1280,
    weeklyPrice: 7490,
    monthlyPrice: 23900,
    depositAmount: 12000,
    mileageLimit: 240,
    city: "Marrakech",
    agencyName: "Agence Marrakech Gueliz",
    address: "Boulevard Abdelkrim Khattabi, Marrakech",
    mainImageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80",
    description: "SUV premium hybride avec un tres bon niveau de finition.",
    seoTitle: "Lexus NX 2024 - Location Marrakech",
    seoDescription: "Location d'une Lexus NX 2024 a Marrakech, haut de gamme et confortable.",
    seoSlug: "lexus-nx-2024-marrakech",
  },
  {
    licensePlate: "AA-117-AA",
    brand: "Seat",
    model: "Ibiza",
    year: 2023,
    category: "CITADINE",
    fuelType: "ESSENCE",
    transmission: "MANUELLE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 220,
    weeklyPrice: 1250,
    monthlyPrice: 3950,
    depositAmount: 1800,
    mileageLimit: 200,
    city: "Essaouira",
    agencyName: "Agence Essaouira Medina",
    address: "Route de Marrakech, Essaouira",
    mainImageUrl: "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80",
    description: "Citadine vive et economique, tres simple a garer en centre-ville.",
    seoTitle: "Seat Ibiza 2023 - Location Essaouira",
    seoDescription: "Location d'une Seat Ibiza 2023 a Essaouira, compacte et pratique.",
    seoSlug: "seat-ibiza-2023-essaouira",
  },
  {
    licensePlate: "AA-118-AA",
    brand: "Volkswagen",
    model: "Golf",
    year: 2024,
    category: "BERLINE",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 450,
    weeklyPrice: 2590,
    monthlyPrice: 8290,
    depositAmount: 3500,
    mileageLimit: 240,
    city: "Rabat",
    agencyName: "Agence Rabat Agdal",
    address: "Avenue Annakhil, Rabat",
    mainImageUrl: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1400&q=80",
    description: "Compacte premium polyvalente, adapte a la ville comme a la route.",
    seoTitle: "Volkswagen Golf 2024 - Location Rabat",
    seoDescription: "Location d'une Volkswagen Golf 2024 a Rabat, elegante et moderne.",
    seoSlug: "volkswagen-golf-2024-rabat",
  },
  {
    licensePlate: "AA-119-AA",
    brand: "Land Rover",
    model: "Range Rover Evoque",
    year: 2024,
    category: "4X4",
    fuelType: "HYBRIDE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 1450,
    weeklyPrice: 8490,
    monthlyPrice: 26900,
    depositAmount: 15000,
    mileageLimit: 220,
    city: "Agadir",
    agencyName: "Agence Agadir Centre",
    address: "Avenue Hassan II, Agadir",
    mainImageUrl: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=80",
    description: "SUV premium au style distinctif et au confort tres haut niveau.",
    seoTitle: "Land Rover Range Rover Evoque 2024 - Location Agadir",
    seoDescription: "Location d'un Land Rover Range Rover Evoque 2024 a Agadir, luxe et caractere.",
    seoSlug: "land-rover-range-rover-evoque-2024-agadir",
  },
  {
    licensePlate: "AA-120-AA",
    brand: "Suzuki",
    model: "Swift",
    year: 2023,
    category: "CITADINE",
    fuelType: "ESSENCE",
    transmission: "MANUELLE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 190,
    weeklyPrice: 1090,
    monthlyPrice: 3450,
    depositAmount: 1500,
    mileageLimit: 180,
    city: "Fes",
    agencyName: "Agence Fes Centre",
    address: "Avenue Hassan II, Fes",
    mainImageUrl: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1400&q=80",
    description: "Citadine legere et economique, ideale pour les petits trajets.",
    seoTitle: "Suzuki Swift 2023 - Location Fes",
    seoDescription: "Location d'une Suzuki Swift 2023 a Fes, compacte et facile a conduire.",
    seoSlug: "suzuki-swift-2023-fes",
  },
  {
    licensePlate: "AA-121-AA",
    brand: "Opel",
    model: "Astra",
    year: 2024,
    category: "BERLINE",
    fuelType: "DIESEL",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 310,
    weeklyPrice: 1790,
    monthlyPrice: 5790,
    depositAmount: 2500,
    mileageLimit: 220,
    city: "Tanger",
    agencyName: "Agence Tanger Marina",
    address: "Boulevard Mohammed VI, Tanger",
    mainImageUrl: "https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=1400&q=80",
    description: "Berline pratique et sobre, tres interessante pour les longs parcours.",
    seoTitle: "Opel Astra 2024 - Location Tanger",
    seoDescription: "Location d'une Opel Astra 2024 a Tanger, sobre et confortable.",
    seoSlug: "opel-astra-2024-tanger",
  },
  {
    licensePlate: "AA-122-AA",
    brand: "Cupra",
    model: "Formentor",
    year: 2024,
    category: "SUV",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 5,
    doors: 5,
    airConditioning: true,
    dailyPrice: 930,
    weeklyPrice: 5490,
    monthlyPrice: 17500,
    depositAmount: 9000,
    mileageLimit: 260,
    city: "Casablanca",
    agencyName: "Agence Casablanca Centre",
    address: "Boulevard Mohammed V, Casablanca",
    mainImageUrl: "https://images.unsplash.com/photo-1517672651691-24622a91b550?auto=format&fit=crop&w=1400&q=80",
    description: "SUV sportif avec une touche premium et un design tres moderne.",
    seoTitle: "Cupra Formentor 2024 - Location Casablanca",
    seoDescription: "Location d'une Cupra Formentor 2024 a Casablanca, sportive et moderne.",
    seoSlug: "cupra-formentor-2024-casablanca",
  },
  {
    licensePlate: "AA-123-AA",
    brand: "Fiat",
    model: "500",
    year: 2023,
    category: "CITADINE",
    fuelType: "ESSENCE",
    transmission: "AUTOMATIQUE",
    seats: 4,
    doors: 3,
    airConditioning: true,
    dailyPrice: 180,
    weeklyPrice: 990,
    monthlyPrice: 3090,
    depositAmount: 1500,
    mileageLimit: 180,
    city: "Essaouira",
    agencyName: "Agence Essaouira Medina",
    address: "Route de Marrakech, Essaouira",
    mainImageUrl: "https://images.unsplash.com/photo-1462396881884-de2c07cb95ed?auto=format&fit=crop&w=1400&q=80",
    description: "Petite voiture urbaine, economique et tres facile a vivre.",
    seoTitle: "Fiat 500 2023 - Location Essaouira",
    seoDescription: "Location d'une Fiat 500 2023 a Essaouira, compacte et elegante.",
    seoSlug: "fiat-500-2023-essaouira",
  },
];

async function getOrCreateBrands(context: Pick<DatabaseContext, "db" | "schema">, brandNames: string[]) {
  const brandRows = await context.db
    .select()
    .from(context.schema.carBrandsTable)
    .where(inArray(context.schema.carBrandsTable.name, brandNames));

  const brandByName = new Map(brandRows.map((brand) => [brand.name.toLowerCase(), brand]));
  const missingBrandNames = brandNames.filter((name) => !brandByName.has(name.toLowerCase()));

  for (const brandName of missingBrandNames) {
    const [created] = await context.db
      .insert(context.schema.carBrandsTable)
      .values({ name: brandName })
      .returning();
    brandByName.set(brandName.toLowerCase(), created);
  }

  return brandByName;
}

async function getOrCreateAgencies(context: Pick<DatabaseContext, "db" | "schema">, agencySeeds: Array<{ name: string; city: string; address: string }>) {
  const cities = [...new Set(agencySeeds.map((agency) => agency.city))];
  const agencyRows = cities.length > 0
    ? await context.db
        .select()
        .from(context.schema.agenciesTable)
        .where(inArray(context.schema.agenciesTable.city, cities))
    : [];

  const agencyByCity = new Map(agencyRows.map((agency) => [agency.city.toLowerCase(), agency]));
  const missingAgencies = agencySeeds.filter((agency) => !agencyByCity.has(agency.city.toLowerCase()));

  for (const agencySeed of missingAgencies) {
    const [created] = await context.db
      .insert(context.schema.agenciesTable)
      .values({
        name: agencySeed.name,
        city: agencySeed.city,
        address: agencySeed.address,
      })
      .returning();
    agencyByCity.set(agencySeed.city.toLowerCase(), created);
  }

  return agencyByCity;
}

export async function ensureDemoFleet(context: Pick<DatabaseContext, "db" | "schema">) {
  const existingRows = await context.db
    .select({ seoSlug: context.schema.carsTable.seoSlug })
    .from(context.schema.carsTable)
    .where(inArray(context.schema.carsTable.seoSlug, demoFleet.map((car) => car.seoSlug)));

  const existingSlugs = new Set(
    existingRows
      .map((row) => row.seoSlug?.trim())
      .filter((value): value is string => Boolean(value)),
  );

  const carsToInsert = demoFleet.filter((car) => !existingSlugs.has(car.seoSlug));
  if (carsToInsert.length === 0) {
    return { inserted: 0, expected: demoFleet.length };
  }

  const brandByName = await getOrCreateBrands(
    context,
    [...new Set(carsToInsert.map((car) => car.brand))],
  );
  const agencySeedsByCity = new Map<string, { name: string; city: string; address: string }>();
  for (const car of carsToInsert) {
    if (!agencySeedsByCity.has(car.city.toLowerCase())) {
      agencySeedsByCity.set(car.city.toLowerCase(), {
        name: car.agencyName,
        city: car.city,
        address: car.address,
      });
    }
  }

  const agencyByCity = await getOrCreateAgencies(
    context,
    [...agencySeedsByCity.values()],
  );

  for (const car of carsToInsert) {
    const brand = brandByName.get(car.brand.toLowerCase());
    const agency = agencyByCity.get(car.city.toLowerCase());

    if (!brand) {
      throw new Error(`Missing brand record for ${car.brand}`);
    }

    if (!agency) {
      throw new Error(`Missing agency record for ${car.city}`);
    }

    await context.db.insert(context.schema.carsTable).values({
      licensePlate: car.licensePlate,
      brand: car.brand,
      brandId: brand.id,
      model: car.model,
      year: car.year,
      category: car.category,
      fuelType: car.fuelType,
      transmission: car.transmission,
      seats: car.seats,
      doors: car.doors,
      airConditioning: car.airConditioning,
      dailyPrice: car.dailyPrice,
      weeklyPrice: car.weeklyPrice,
      monthlyPrice: car.monthlyPrice,
      depositAmount: car.depositAmount,
      mileageLimit: car.mileageLimit,
      city: car.city,
      agencyId: agency.id,
      description: car.description,
      seoTitle: car.seoTitle,
      seoDescription: car.seoDescription,
      seoSlug: car.seoSlug,
      insuranceIncluded: true,
      status: "AVAILABLE",
      mainImageUrl: car.mainImageUrl,
    } as any);
  }

  return { inserted: carsToInsert.length, expected: demoFleet.length };
}
