const colors = {
  light: {
    text: "#282f3d",
    tint: "#df5820",
    background: "#faf8f5",
    foreground: "#282f3d",
    card: "#ffffff",
    cardForeground: "#282f3d",
    primary: "#df5820",
    primaryForeground: "#ffffff",
    secondary: "#1e3b5a",
    secondaryForeground: "#ffffff",
    muted: "#ede8e1",
    mutedForeground: "#7a7268",
    accent: "#ede8e1",
    accentForeground: "#282f3d",
    destructive: "#f03333",
    destructiveForeground: "#ffffff",
    border: "#d8cfc4",
    input: "#d8cfc4",
    success: "#16a34a",
    successForeground: "#ffffff",
    warning: "#d97706",
    warningForeground: "#ffffff",
    info: "#2563eb",
    infoForeground: "#ffffff",
  },
  dark: {
    text: "#faf8f5",
    tint: "#df5820",
    background: "#151c2e",
    foreground: "#faf8f5",
    card: "#1c2538",
    cardForeground: "#faf8f5",
    primary: "#df5820",
    primaryForeground: "#ffffff",
    secondary: "#1e3b5a",
    secondaryForeground: "#ffffff",
    muted: "#222d3f",
    mutedForeground: "#8e96a3",
    accent: "#222d3f",
    accentForeground: "#faf8f5",
    destructive: "#7d1d1d",
    destructiveForeground: "#faf8f5",
    border: "#222d3f",
    input: "#334256",
    success: "#16a34a",
    successForeground: "#ffffff",
    warning: "#d97706",
    warningForeground: "#ffffff",
    info: "#2563eb",
    infoForeground: "#ffffff",
  },
  radius: 12,
};

export default colors;
